[package]
name = "vulkan-graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.3"
gpu-allocator = "0.25.0"
nalgebra = "0.32.3"
winit = "0.28.7"
